### ISSUE TITLE
Apply APO Defaults is failing with a cocina validation error

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#3648] opened 2022-03-02 19:59 UTC
See https://app.honeybadger.io/projects/50568/faults/84314037

Attempt to apply APO defaults for this object: https://argo-qa.stanford.edu/view/druid:bb408qn5061

Replicate on the rails console in QA:

```
Dor::Services::Client.object('druid:bb408qn5061').apply_admin_policy_defaults

Dor::Services::Client::UnexpectedResponse: Internal Server Error: 500 (Response from dor-services-app did not contain a body.                         Check honeybadger for dor-services-app for backtraces,                         and look into adding a `rescue_from` in dor-services-app                         to provide more details to the client in the future)
from /opt/app/lyberadmin/argo/shared/bundle/ruby/3.0.0/gems/dor-services-client-8.0.0/lib/dor/services/client/versioned_service.rb:36:in `raise_exception_based_on_response!'
```

**Comment by peetucket** [comment] 2022-03-02 19:59
Currently blocking testing of https://github.com/sul-dlss/argo/pull/3182

**Comment by mjgiarlo** [comment] 2022-03-02 20:18
Error: 
```
Cocina::Models::ValidationError: {"access"=>"world", "download"=>"world", "readLocation"=>"music", "copyright"=>"This work is copyrighted by the creator.", "useAndReproductionStatement"=>"This document is available only to the Stanford faculty, staff and student community.", "license"=>"https://creativecommons.org/publicdomain/zero/1.0/legalcode"} isn't one of in #/components/schemas/Access
```

**Comment by mjgiarlo** [comment] 2022-03-02 20:23
To reproduce this on `dor-services-qa`:

```
> item = CocinaObjectStore.find(druid) && item.new(access: item.access.new("access"=>"world", "download"=>"world", "readLoc
ation"=>"music", "copyright"=>"This work is copyrighted by the creator.", "useAndReproductionStatement"=>"This document is available o
nly to the Stanford faculty, staff and student community.", "license"=>"https://creativecommons.org/publicdomain/zero/1.0/legalcode"))
```

**Comment by mjgiarlo** [comment] 2022-03-02 20:46
# Analysis

I think the problem is that https://github.com/sul-dlss/dor-services-app/blob/main/app/services/apply_admin_policy_defaults.rb#L70 is essentially a merge operation: it applies the APO defaults, but if the item has keys that aren't in the APO defaults (like `readLocation` or `controlledDigitalLending` or `license`, etc.), those are not reset. Which results in invalid access settings.

This makes me wonder if applying APO defaults should be a complete reset of item access to prevent invalid access settings.

Question for @andrewjbtw (cc: @jcoyne @justinlittman): if an APO has this as default access:

```
{
:access=>"world", 
:copyright=>"This work is copyrighted by the creator.", 
:download=>"world", 
:useAndReproductionStatement=>"This document is available only to the Stanford faculty, staff and student community."
}
```

and a member item having APO defaults applied has this as its current access:

```
{
:access=>"location-based", 
:download=>"location-based", 
:readLocation=>"music", 
:copyright=>"This work is copyrighted by the creator....", 
:useAndReproductionStatement=>"Changed it", 
:license=>"https://creativecommons.org/publicdomain/zero/1.0/legalcode"
}
```

... should the item's `readLocation` be nulled? and what about the license? (and CDL if present?)

Ultimately, should applying APO defaults be a reset or a smart merge?

**Comment by justinlittman** [comment] 2022-03-02 20:50
Is ApplyAdminPolicyDefaults a dupe of https://github.com/sul-dlss/dor-services-app/blob/main/app/services/access_merge_service.rb?

**Comment by mjgiarlo** [comment] 2022-03-02 20:51
@justinlittman in this case, Andrew says we don't want to merge, we want to reset/overwrite. So maybe not?

**Comment by jcoyne** [comment] 2022-03-02 20:52
It sounds like there are two scenarios with different requirements.  When registering, it's a merge onto what is already applied unless it is provided (ApplyAdminPolicyDefault).  In the "Apply APO Defaults" it's "clear the object and overwrite", which we maybe don't have a correct method for?

**Comment by peetucket** [comment] 2022-03-02 21:12
Note: tis is the class that is being used when the DSA call is made to apply APO defaults: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/apply_admin_policy_defaults.rb

(see https://github.com/sul-dlss/dor-services-app/blob/main/app/controllers/admin_policy_defaults_controller.rb and https://github.com/sul-dlss/dor-services-app/blob/main/config/routes.rb#L46)

**Closed** 2022-03-02 21:30 UTC
Labels: bug
