### ISSUE TITLE
Migrate stacks location out of Fedora 3

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#2764] opened 2021-04-26 15:25 UTC
Currently we store this for some objects (possibly only web archives?) in the contentMetadata like this:
```
<contentMetadata type="file" stacks="/web-archiving-stacks/data/collections/mm553tf6423" id="druid:wp600gp2149">
```

On sdr-deploy you can find all of these by doing:
```
find  /opt/app/deploy/dor-services-app/cache -name '*.zip'|xargs -I '{}'  unzip -cq '{}' contentMetadata.xml|grep  'stacks="'|grep -v "filename not matched"
```

It's not clear to me that this information should be in the preserved object and it seems more like configuration that could be done per object type or per APO.

**Comment by andrewjbtw** [comment] 2021-04-26 15:56
Yes, this definitely looks like configuration information to me. Until now, I had thought that the configuration of the was-robots was how web archive crawl data got to the web archiving stacks.

**Comment by ndushay** [comment] 2021-04-26 17:57
should the info for web archive WARCs be roundtripped (fedora -> cocina -> fedora? If not we should create a ticket to add normalization code for the differences.

**Comment by justinlittman** [comment] 2021-12-17 14:05
Dupe of #3121 / #3082

**Closed by justinlittman** 2021-12-17 14:05 UTC
