### ISSUE TITLE
Map parallel identifiers

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2267] opened 2021-02-20 17:47 UTC
For example, https://argo.stanford.edu/view/druid:cf645zr8941:
```
<identifier altRepGroup="09">(DLC) 99115020</identifier>
    <identifier altRepGroup="09">(OCoLC)8735405</identifier>
```

**Comment by arcadiafalcone** [comment] 2021-02-22 18:14
I think this will be fixed by refreshing from source with the current MARC2MODS XSLT (which I can't do myself because it's a Project Phoenix item).

**Comment by arcadiafalcone** [comment] 2021-02-22 19:25
Confirmed fixed by refresh.

**Closed by arcadiafalcone** 2021-02-22 19:25 UTC
Labels: mappings
