### ISSUE TITLE
Valid MODS fails validation

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2320] opened 2021-02-23 19:19 UTC
When validating the MODS-Cocina roundtrip, the MODS validation identifies records where the only subelement of `originInfo` is `frequency` as invalid MODS. It should be passed as valid.

Examples:
druid:gm290dm5855
druid:nh309wq5492

**Comment by justinlittman** [comment] 2021-02-24 18:33
I think the problem is `<originInfo altRepGroup="06"/>` (i.e., empty originInfo elements).

**Comment by peetucket** [comment] 2021-03-29 16:44
Let's try and re-validate these and see if further action is needed

**Comment by ndushay** [comment] 2021-03-31 20:53
```
$  bin/validate-cocina-roundtrip -d 'druid:gm290dm5855'
...
Traceback (most recent call last):
bin/validate-cocina-roundtrip:31:in `<main>': undefined method `url' for nil:NilClass (NoMethodError)

$  bin/validate-cocina-roundtrip -d 'druid:nh309wq5492'
...
Traceback (most recent call last):
bin/validate-cocina-roundtrip:31:in `<main>': undefined method `url' for nil:NilClass (NoMethodError)

**Comment by ndushay** [comment] 2021-03-31 22:16
Arcadia says these 2 records have had their descriptive metadata refreshed and thus mapped to cocina anew and she is no longer concerned about the validity of the descriptive metadata in Cocina.   She says if there is a problem, it will surface again.

Thus, I am closing this ticket.

Note that the problem mapping to cocina above is seemingly not related to MODS and will likely appear in other contexts, so again, not worrying about solving for this text.

**Closed by ndushay** 2021-03-31 22:16 UTC
Labels: mappings
