### ISSUE TITLE
DATA Error: Missing title - when running integration tests in stage

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor-services-app#2759] opened 2021-04-22 22:38 UTC
https://app.honeybadger.io/projects/50568/faults/73649200

The above error is reported when running this integration test that fails on embargo date:

```
❯ bundle exec rspec spec/features/deposit_via_hydrus_spec.rb
Run options: exclude {:indexing=>true, :skip_for_default=>true}

Randomized with seed 20312

Use Hydrus to deposit an item
  is expected to eq 1 (FAILED - 1)

Failures:

  1) Use Hydrus to deposit an item is expected to eq 1
     Failure/Error: expect(embargo_nodes.size).to eq 1
     
       expected: 1
            got: 0
     
       (compared using ==)
     # ./spec/features/deposit_via_hydrus_spec.rb:158:in `expect_embargo_date_in_purl'
     # ./spec/features/deposit_via_hydrus_spec.rb:141:in `block (2 levels) in <top (required)>'

Finished in 1 minute 13.52 seconds (files took 1.3 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/deposit_via_hydrus_spec.rb:15 # Use Hydrus to deposit an item is expected to eq 1

Randomized with seed 20312
```

**Comment by jmartin-sul** [comment] 2021-04-24 01:59
i think this might be working now?  i pulled the latest infrastructure-integration-test code and ran this test against stage 5 times in the last hour or so.  it succeeded on 3 of those runs.  on the failed attempt where i was paying close attention to the test browser, and i was able to catch the druid, i looked at what was happening on the line that was failing in the integration test (last line of this snippet):  https://github.com/sul-dlss/infrastructure-integration-test/blob/ffca238f95e99a4ed4bf277184c7461e3dec6aea/spec/features/deposit_via_hydrus_spec.rb#L120-L122

```ruby
    # check Argo facet field (indexed embargo date) with 3 day embargo
    visit "#{Settings.argo_url}/catalog?search_field=text&q=#{bare_druid}"
    reload_page_until_timeout!(text: 'Embargo Release Date')
```

and i noticed that when the test timed out, it was still hung on the object view page, which is the prior page it visits, on [line 111](https://github.com/sul-dlss/infrastructure-integration-test/blob/ffca238f95e99a4ed4bf277184c7461e3dec6aea/spec/features/deposit_via_hydrus_spec.rb#L111).

when i went to look at the druid in question in argo, and i tried visiting the page the test _should've_ landed on before executing line 122: https://argo-stage.stanford.edu/catalog?search_field=text&q=nd250db0319

things looked good, and the text that the test searches for was there:
<img width="844" alt="Screen Shot 2021-04-23 at 6 46 34 PM" src="https://user-images.githubusercontent.com/7741604/115943432-cbee2980-a464-11eb-97d5-954ea8f49059.png">

altogether, this makes me think that the cause of that run's failure was the usual intermittent (capybara? webdriver?) test execution flakiness.  esp since it completed successfully three times in a row.

on the other failed run, i wasn't paying close attention to the test execution, and didn't note the druid to go look at it in argo.  but the failure was the same:

```
Randomized with seed 59675

Use Hydrus to deposit an item
/Users/suntzu/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:54: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/suntzu/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/driver.rb:31: warning: The called method `new' is defined here
SUNet ID: suntzu
Password: 
  is expected to eq "2021-10-23T00:00:00Z" (FAILED - 1)

Failures:

  1) Use Hydrus to deposit an item is expected to eq "2021-10-23T00:00:00Z"
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: break if page.has_text?(text, wait: 1)
          
          Timeout::Error:
            execution expired
          # ./spec/support/page_helpers.rb:16:in `block (2 levels) in reload_page_until_timeout!'
          # ./spec/support/page_helpers.rb:6:in `loop'
          # ./spec/support/page_helpers.rb:6:in `block in reload_page_until_timeout!'
          # ./spec/support/page_helpers.rb:5:in `reload_page_until_timeout!'
          # ./spec/features/deposit_via_hydrus_spec.rb:122:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: Unable to find WebDriverError@chrome://marionette/content/error.js to read failed line
          Selenium::WebDriver::Error::NoSuchAlertError:
          # WebDriverError@chrome://marionette/content/error.js:181:5
          # NoSuchAlertError@chrome://marionette/content/error.js:382:5
          # GeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:2722:11
          # GeckoDriver.prototype.dismissDialog@chrome://marionette/content/driver.js:2625:8
          # despatch@chrome://marionette/content/server.js:291:40
          # execute@chrome://marionette/content/server.js:264:16
          # onPacket/<@chrome://marionette/content/server.js:237:20
          # onPacket@chrome://marionette/content/server.js:238:9
          # _onJSONObjectReady/<@chrome://marionette/content/transport.js:504:20
```

i tried on -qa, but it appears i don't have permission to create hydrus collections there.

ok, actually, i think there are two issues here (or i was just confused about the primary focus of this ticket 🙂):  i do see new instances of the honeybadger alert in the description, associated with the druids from my test runs just now.  so i'll investigate those.  but the integration test in question at least seems to pass as consistently as any other for me.

**Comment by jmartin-sul** [comment] 2021-04-24 01:59
ok, actually, i think there are two issues here (or i was just confused about the primary focus of this ticket 🙂):  i do see new instances of the honeybadger alert in the description, associated with the druids from my test runs just now.  so i'll investigate those.  but the integration test in question at least seems to pass as consistently as any other for me.

**Comment by ndushay** [comment] 2021-04-26 16:19
Andrew says:  there is no title when hydrus objects are created;  so this will always happen for a hydrus object.  Perhaps confer with Andrew if this should be fixed for integration tests?  Or is it the OTHER thing that's broken?

**Comment by jcoyne** [comment] 2021-04-26 21:43
I'm very doubtful that the data error is related to the of the problem where the embargo is not correctly displaying in PURL.  We've had that data error for months and months without problems.

**Comment by jmartin-sul** [comment] 2021-04-29 17:46
post-standup discussion w/ @andrewjbtw -- we're going to close this, as the alert is a minor annoyance for now, and it'll go away once we retire hydrus for H2 (because hydrus registers things before the user has a chance to enter a title, and H2 requires title entry before collection or item registration).  this issue is not actually creating bad data in the long term or preventing people from doing work.

**Closed by jmartin-sul** 2021-04-29 17:46 UTC
Labels: bug
