### ISSUE TITLE
notify on inconsistent types for names in same altRepGroup [was: Don't normalize name type="corporate" to name type="conference"]

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2456] opened 2021-03-09 22:55 UTC
mx303pc7527

**Comment by jmartin-sul** [comment] 2021-04-06 05:56
@arcadiafalcone, sorry this got tied up in progress without actually moving forward -- i picked this up, got pulled back to working on an H2 feature, had a busy first responder week, and then got pulled back to finishing that H2 feature.

I started back in on this on Friday, and after getting a bit stuck, paired with @ndushay this afternoon.  We were both a bit unsure how to proceed since we weren't sure what exactly the desired Cocina output is in this case, and since the druid mentioned in the issue description has been remediated to no longer have this issue (maybe we think).

I did have a copy of the old problematic desc metadata fragments that were causing trouble, and it seemed to me that the issue only occurs when there are two different `name` elements, one with `type="conference"` and one with `type="corporate"`, e.g.:

```xml
<name type="conference" altRepGroup="01" script="Latn">
  <namePart>Zhonghua gong nong bing Suwei'ai quan guo dai biao da hui 1931 : Ruijin)</namePart>
</name>
<name type="corporate" altRepGroup="01" script="Latn">
<!-- snip some other desc metadata in between -->
<namePart>&#x4E2D;&#x83EF;&#x5DE5;&#x8FB2;&#x5175;&#x8607;&#x7DAD;&#x57C3;&#x5168;&#x570B;&#x4EE3;&#x8868;&#x5927;&#x6703;</namePart>
  <namePart>(1st : 1931 : Ruijin)</namePart>
</name>
```

If there is only a `name type="corporate"`, that seems to work fine, assuming the Cocina `type` in that case should be `'organization'`.

So, questions:

1. Have you seen cases where the Cocina `type` is incorrect when only one `name` element is in play?
2. Is there other data like this in production, now that mx303pc7527 seems to have been remediated?  Is mx303pc7527 still producing incorrect contributor Cocina?
3. I'm pretty unfamiliar with `altRepGroup` usage (Naomi gave me a short primer this afternoon), but we were wondering whether the `name` elements in this example's original desc metadata were meant to have a structured relationship?
4. If there is still problematic data like this in production, would it be acceptable to alert and to keep producing the same Cocina output we do now?
5. If no, and we should fix the Cocina output, what's the desired JSON look like?  Before pairing this afternoon, I'd had something like:

```ruby
      let(:cocina) do
        {
          contributor: [
            {
              name: [
                value: "Zhonghua gong nong bing Suwei'ai quan guo dai biao da hui 1931 : Ruijin)",
                valueLanguage: {
                  valueScript: {
                    code: 'Latn',
                    source: {
                      code: 'iso15924'
                    }
                  }
                }
              ],
              type: 'conference'
            },
            {
              name: [
                structuredValue: [
                  {
                    value: '中華工農兵蘇維埃全國代表大會',
                    type: 'name'
                  },
                  {
                    value: '(1st : 1931 : Ruijin)',
                    type: 'name'
                  }
                ],
                valueLanguage: {
                  valueScript: {
                    code: 'Latn',
                    source: {
                      code: 'iso15924'
                    }
                  }
                }
              ],
              type: 'organization'
            }
          ]
        }
      end
```

which was basically a cobbling together of the `conference` and `corporate` output from their respective separate examples.

I introduced some mapping regressions on my WIP branch with my initial attempts at producing the above JSON, and in pairing to try fixing that, Naomi persuaded me it was better to just get some clarification on all the above before pushing on this anymore.

Thanks for any further info you can give!

**Comment by arcadiafalcone** [comment] 2021-04-06 17:26
After some further digging I think we can continue to alert this as a data problem rather than changing the mapping. I haven't been able to find any non-altRepGroup examples, so I think what's happening is that the code assumes that all names sharing an altRepGroup have the same type (which they should), so when the types differ it looks like the roundtrip is failing.

**Comment by ndushay** [comment] 2021-04-06 20:34
so if we're alerting on this now, can this ticket be closed?

**Comment by arcadiafalcone** [comment] 2021-04-06 20:35
Yes.

**Comment by ndushay** [comment] 2021-04-06 20:40
@jmartin-sul so if you can check that we ARE alerting on this, and if so, close this, and if not, write that code do a PR to close this ticket ... that would do it

**Closed** 2021-04-08 17:55 UTC
Labels: mappings
