### ISSUE TITLE
APO administrativeMetadata  <accessioning> and <assembly> and <relationships>

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3359] opened 2022-02-08 21:03 UTC
@andrewjbtw @justinlittman  should we be dropping `<accessioning>` `<assembly>` `<relationships>` in administrative metadata (remove via normalization), or should it be mapped to Cocina?

Please make sure to test this with the druids mentioned below and with druids.apo.txt.

bx911tp9024:

```xml
 Original XML for administrativeMetadata:
<administrativeMetadata>
...
  <accessioning>
    <workflow id="accessionWF"/>
  </accessioning>
  <dissemination>
    <workflow id="releaseWF"/>
  </dissemination>
</administrativeMetadata>

Roundtripped XML for administrativeMetadata:
```
<administrativeMetadata>
...
  <dissemination>
    <workflow id="releaseWF"/>
  </dissemination>
</administrativeMetadata>
```

cb081vd1895:

```xml
Original XML for administrativeMetadata:
<administrativeMetadata objectId="druid:cb081vd1895">
...
  <relationships xmlns:fedora-rel="info:fedora/fedora-system:def/relations-external#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <fedora-rel:isMemberOf rdf:resource="info:fedora/druid:kh020kr4702"/>
    <fedora-rel:isMemberOfCollection rdf:resource="info:fedora/druid:kh020kr4702"/>
  </relationships>
  <registration>
    <workflow id="registrationWF"/>
  </registration>
  <assembly>
    <workflow id="assemblyWF"/>
  </assembly>
  <accessioning>
    <workflow id="accessionWF"/>
  </accessioning>
</administrativeMetadata>

Normalized original XML for administrativeMetadata:
<administrativeMetadata>
...
  <relationships xmlns:fedora-rel="info:fedora/fedora-system:def/relations-external#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <fedora-rel:isMemberOf rdf:resource="info:fedora/druid:kh020kr4702"/>
    <fedora-rel:isMemberOfCollection rdf:resource="info:fedora/druid:kh020kr4702"/>
  </relationships>
  <registration>
    <workflow id="registrationWF"/>
  </registration>
  <assembly>
    <workflow id="assemblyWF"/>
  </assembly>
  <accessioning>
    <workflow id="accessionWF"/>
  </accessioning>
</administrativeMetadata>

Roundtripped XML for administrativeMetadata:

<administrativeMetadata>
  <registration>
    <workflow id="registrationWF"/>
  </registration>
</administrativeMetadata>
```

**Comment by andrewjbtw** [comment] 2022-02-08 21:50
I have no idea. One way to test would be to add and drop them in stage and see what happens. It's not clear from the Chimera docs what was implemented for this datastream:
https://consul.stanford.edu/display/chimera/Admin+Policy+Object+-+datastreams+and+content

I believe the assemblyWF and accessionWF both currently run the same way regardless of what any APO says. I think the question comes down to: when accessioning (or assembly, or preassembly, or whatever robot comes first) starts, is there any point during the chain of workflows where the instruction for what step to run next comes from the APO rather than from the workflow itself?

**Comment by justinlittman** [comment] 2022-02-08 21:52
@jcoyne Any thoughts?

**Comment by justinlittman** [comment] 2022-02-10 22:28
Dupe of #3322

**Closed by justinlittman** 2022-02-10 22:28 UTC
Labels: question, mappings
